### ISSUE TITLE
Gulp exits on sass syntax error

### ISSUE THREAD

**Issue by patdunlavey** [commonmedia/drupal-gulp-starter#1]
Any time I inadvertently save a .scss file with a syntax error, gulp watch exits. Instead, it should report the error, and keep watching.

**Comment by serundeputy** [comment]
Thanks @patdunlavey !

@imahoney I think this is a good change; looping you in so you are aware of it.

If you agree with the change merge it in!

thanks,
~Geoff

**Comment by JamesChevalier** [comment]
https://github.com/commonmedia/drupal-gulp-starter/pull/2 fixes this
